### ISSUE TITLE
One does not simply alter something in the vendors folder

### ISSUE THREAD

**Issue by mathewrapid** [lunistore/akeneo-connector-base#3]
> Note: This will need a small patch in method
> `Pim\Bundle\ImportExportBundle\Twig\NormalizeConfigurationExtension::normalizeValueFilter()`

In many cases (or almost always) the deployment processes do not use the developers local vendors content and/or use the `composer.lock` file to install the correct dependencies. This results into that any changes made in the vendors folder will get overwritten by composer.

I'd recommend to add your own `NormalizeConfigurationExtension` class and just to override the services class parameter `pim_import_export.twig.normalize_configuration_extension.class` to point to it. This way the changes won't get lost.

**Comment by gplanchat** [comment]
Yes. You have a good point.

Better than this, I just made a PR to Akeneo itself akeneo/pim-community-dev/pull/4529

**Comment by gplanchat** [comment]
The fix was merged on https://github.com/akeneo/pim-community-dev/commit/650b05ce2a7d0d57db38be728b29fc6fed726824
